# Generated by Django 3.0.3 on 2020-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200221_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='to_show',
            field=models.BooleanField(default=False),
        ),
    ]
