# Generated by Django 3.0.3 on 2020-02-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_to_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='to_show',
            field=models.BooleanField(default=True),
        ),
    ]
