# Generated by Django 3.0.3 on 2020-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200221_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='angry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='energy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='happy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='stressy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='worry',
            field=models.BooleanField(default=False),
        ),
    ]
