# Generated by Django 3.0.3 on 2020-02-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200221_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.CharField(default='tester', max_length=30),
            preserve_default=False,
        ),
    ]
